modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
issueTrackerURL="http://github.com/itsmeow/QuickTeleports/issues" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/quickteleports" #optional
logoFile="quickteleports.png" #optional
credits="its_meow, for programming, ideas, design, and leading" #optional
authors="its_meow" #optional
[[mods]] #mandatory
modId="quickteleports" #mandatory
version="${file.jarVersion}" #mandatory
displayName="QuickTeleports" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
This mod adds a quick and easy way to send tp requests with /tpa and /tpaccept'''